SELECT
  r.FUNCTION_NAME, r.FORM_NAME,
  r.SEQUENCE, r.DESCRIPTION, r.RULE_TYPE,
  r.TRIGGER_EVENT
   ||' :: ' ||r.TRIGGER_OBJECT
   ||' :: ' ||r.CONDITION
  AS CONDITION,
  r.ENABLED, r.CREATION_DATE, r.LAST_UPDATE_DATE,
  a.SEQUENCE, a.SUMMARY,
  a.ACTION_TYPE
    ||' :: '||Decode(a.ACTION_TYPE, 'M',a.MESSAGE_TYPE, 'B',a.BUILTIN_TYPE)
    ||' :: '||a.OBJECT_TYPE||'.'||a.TARGET_OBJECT
  AS ACTION_TYPE_TARGET,
  a.ARGUMENT_TYPE||': '||(
    SELECT PROPERTY_NAME
    FROM apps.FND_FORM_CUSTOM_PROP_LIST
    WHERE FIELD_TYPE=a.OBJECT_TYPE
      AND ARGUMENT_TYPE=a.ARGUMENT_TYPE
      AND PROPERTY_ID=a.PROPERTY_NAME
  ) AS ARGUMENT_TYPE,
  Decode(a.ACTION_TYPE,
    'M',a.MESSAGE_TEXT, 'B',a.BUILTIN_ARGUMENTS,
    'P',Decode(a.PROPERTY_VALUE,'4','TRUE','5','FALSE',a.PROPERTY_VALUE)
  ) AS ACTION_TEXT_VALUE,
  a.ENABLED, a.CREATION_DATE, a.LAST_UPDATE_DATE
FROM apps.FND_FORM_CUSTOM_RULES r, apps.FND_FORM_CUSTOM_ACTIONS a
WHERE 1 = 1
  AND r.FUNCTION_NAME = 'RCV_RCVRCERC'
  --AND r.CREATED_BY = -1
  AND r.LAST_UPDATE_DATE > SYSDATE-7
  AND a.RULE_ID = r.ID
ORDER BY r.FUNCTION_NAME, r.FORM_NAME,
  r.SEQUENCE, a.SEQUENCE
